#!/bin/bash
#
# muutujate kasutamise näide
#
# defineerin muutuja ja omistame väärtuse
# väärtus saadakse whoami käsust
kasutaja=`whoami`
# väljastame muutuja väärtus koos seletusega
echo "Tere, $kasutaja!"
# loome ja väljastame kella
kell=`date +"%H:%M"`
echo "Kell on $kell"
# loome ja väljastame kuupäeva
kuupaev=`date +"%d. %B"`
echo "Täna on $kuupaev"
