#!/bin/bash
#
# muutujate kasutamise näide
#
# defineerin muutuja ja omistame väärtuse
# väärtus saadakse whoami käsust
kasutaja=`whoami`
# väljastame muutuja väärtus koos seletusega
echo "Tere, $kasutaja!"
# loome ja väljastame kella
kuupaev=`date +"%d. %B %H:%M"`
echo "Tänane kuupäev ja kell on $kuupaev"
