#!/bin/bash
#
# muutujate kasutamise näide
#
# defineerin muutuja ja omistame väärtuse
# väärtus saadakse whoami käsust
kasutaja=`whoami`
# väljastame muutuja väärtus koos seletusega
echo "Tere, $kasutaja"
